export const MACHINE_MODELS = [
  "Soprano ICE Platinum",
  "Soprano Titanium",
  "Alma Harmony",
  "Helios",
  "Picolo",
  "Cocoon Elysion",
  "Aldix Smart Laser",
  "Pento 9900",
  "PrimeLase HR",
  "PrimeLase Excel",
  "PrimeLase Excel HR",
  "Soprano Platinum",
  "Soprano Titanium Special Edition",
  "Aldix (Triodus)",
  "PrimeLase",
  "Elysion",
  "PicoLo",
  "Splendor X",
  "Pento",
  "Clearlight IPL",
  "Fraction CO2",
  "Mezotix",
  "IOXO Laser",
  "IOXO Microneedling",
  "Focus Dual",
  "Ultraformer III",
  "Powershape 2",
  "Indiba",
  "CMSlim",
  "Coolshaping 2",
  "Hydra Beauty 2",
  "Dermadrop",
  "Carbomed",
  "Cryopen",
  "CryoIQ",
  "Reoxy",
  "Oxyhelp",
  "Omega PDT",
  "Eskimo Luftkylare",
  "TBH Röksug"
];