export const MACHINE_MODELS = [
  "Aldix (Triodus)",
  "Aldix Smart Laser",
  "Alma Harmony",
  "Carbomed",
  "Clearlight IPL",
  "CMSlim",
  "Coolshaping 2",
  "CoolTech",
  "CryoIQ",
  "Cryopen",
  "Dermadrop",
  "Elysion",
  "Eskimo Luftkylare",
  "Focus Dual",
  "Fraction CO2",
  "Helios III",
  "Helius",
  "Hydra Beauty 2",
  "Indiba",
  "IOXO Laser",
  "IOXO Microneedling",
  "Mezotix",
  "Omega PDT",
  "Oxyhelp",
  "Pento",
  "Pento 9900",
  "PicoLo",
  "Powershape 2",
  "PrimeLase",
  "PrimeLase Excel",
  "PrimeLase Excel HR",
  "PrimeLase HR",
  "Reoxy",
  "Sinclair Elysion",
  "Soprano ICE Platinum",
  "Soprano Platinum",
  "Soprano Titanium",
  "Soprano Titanium Special Edition",
  "Splendor X",
  "TBH Röksug",
  "Ultraformer III"
];