export const machineServiceDetails = {
  "Soprano ICE Platinum": {
    title: "Standardservice och underhåll – Soprano ICE Platinum / Titanium",
    details: [
      "Byte av Avjoniseringsfilter",
      "Byte av mekaniskpartikelfilter",
      "Byte av steriliserande UV-lampa",
      "Byte av CPC-kopplingar till filter",
      "Påfyllning av destillerat avjoniserat kylvätska",
      "Spolning av pneumatisk krets",
      "Läckagekontroll",
      "Kontroll av luftintagsfilter",
      "Lasereffektmätning",
      "Rengöring av värmeväxlare",
      "Rengörning av Switchade nätaggret",
      "Kontroll av nödstopp och interlock",
      "Upprättande av serviceprotokoll",
      "Serviceuppmärkning av utrustning",
      "Kontroll av säkerhetsrem",
      "20 % på arbetstid för övriga reparationer",
      "20 % på resekostnader"
    ],
    additionalInfo: "Pris: 600 kr/månad"
  },
  "Soprano Titanium": {
    title: "Standardservice och underhåll – Soprano ICE Platinum / Titanium",
    details: [
      "Byte av Avjoniseringsfilter",
      "Byte av mekaniskpartikelfilter",
      "Byte av steriliserande UV-lampa",
      "Byte av CPC-kopplingar till filter",
      "Påfyllning av destillerat avjoniserat kylvätska",
      "Spolning av pneumatisk krets",
      "Läckagekontroll",
      "Kontroll av luftintagsfilter",
      "Lasereffektmätning",
      "Rengöring av värmeväxlare",
      "Rengörning av Switchade nätaggret",
      "Kontroll av nödstopp och interlock",
      "Upprättande av serviceprotokoll",
      "Serviceuppmärkning av utrustning",
      "Kontroll av säkerhetsrem",
      "20 % på arbetstid för övriga reparationer",
      "20 % på resekostnader"
    ],
    additionalInfo: "Pris: 600 kr/månad"
  },
  "Aldix (Triodus)": {
    title: "Standardservice och underhåll – Aldix (Triodus)",
    details: [
      "Byte av pneumatisk avjoniseringsfilter A",
      "Byte av pneumatisk avjoniseringsfilter B",
      "Byte av snabbkopplingar till filter",
      "Påfyllning av destillerat avjoniserat kylvätska",
      "Spolning av pneumatisk krets",
      "Läckagekontroll",
      "Kontroll av luftintagsfilter",
      "Lasereffektmätning",
      "Rengöring av värmeväxlare",
      "Rengörning av Switchade nätaggret",
      "Kontroll av nödstopp och interlock",
      "Upprättande av serviceprotokoll",
      "Serviceuppmärkning av utrustning",
      "Kontroll av säkerhetsrem",
      "20 % på arbetstid för övriga reparationer",
      "20 % på resekostnader"
    ],
    additionalInfo: "Pris: 549 kr/månad"
  },
  "PrimeLase": {
    title: "Standardservice och underhåll – PrimeLase",
    details: [
      "Byte av vattenfilter för intern vattenkrets",
      "Byte av vattenfilter för tip-kylningssystem",
      "Byte av vattenfilter för diodkylningssystem",
      "Påfyllning av destillerat avjoniserat kylvätska med glykolblandning",
      "Spolning av pneumatisk krets",
      "Läckagekontroll",
      "Kontroll av luftintagsfilter",
      "Lasereffektmätning",
      "Rengöring av värmeväxlare",
      "Rengörning av Switchade nätaggret",
      "Kontroll av nödstopp och interlock",
      "Upprättande av serviceprotokoll",
      "Serviceuppmärkning av utrustning",
      "Kontroll av säkerhetsrem",
      "20 % på arbetstid för övriga reparationer",
      "20 % på resekostnader"
    ],
    additionalInfo: "Pris: 679 kr/månad"
  },
  "Elysion": {
    title: "Standardservice och underhåll – Elysion",
    details: [
      "Byte av mekanisk vattenfilter",
      "Påfyllning av destillerat avjoniserat kylvätska med glykolblandning",
      "Spolning av pneumatisk krets",
      "Läckagekontroll",
      "Kontroll av luftintagsfilter",
      "Lasereffektmätning",
      "Rengöring av värmeväxlare",
      "Rengörning av Switchade nätaggret",
      "Kontroll av nödstopp och interlock",
      "Upprättande av serviceprotokoll",
      "Serviceuppmärkning av utrustning",
      "Kontroll av säkerhetsrem",
      "20 % på arbetstid för övriga reparationer",
      "20 % på resekostnader"
    ],
    additionalInfo: "Pris: 419 kr/månad"
  },
  "PicoLo": {
    title: "Standardservice och underhåll – PicoLo",
    details: [
      "Byte av vattenfiltersystem",
      "Påfyllning av destillerat avjoniserat kylvätska",
      "Spolning av pneumatisk krets",
      "Läckagekontroll",
      "Kontroll av luftintagsfilter",
      "Lasereffektmätning",
      "Rengöring av värmeväxlare",
      "Rengörning av Switchade nätaggret",
      "Kontroll av nödstopp och interlock",
      "Upprättande av serviceprotokoll",
      "Serviceuppmärkning av utrustning",
      "Kontroll av säkerhetsrem",
      "Kontroll av possitionering av ledljus",
      "Kontroll av träffbildsmönster",
      "Kontroll av alla handneheters linser",
      "20 % på arbetstid för övriga reparationer",
      "20 % på resekostnader"
    ],
    additionalInfo: "Pris: 419 kr/månad"
  },
  "Helios": {
    title: "Standardservice och underhåll – Helios",
    details: [
      "Byte av vattenfiltersystem",
      "Påfyllning av destillerat avjoniserat kylvätska",
      "Spolning av pneumatisk krets",
      "Läckagekontroll",
      "Kontroll av luftintagsfilter",
      "Lasereffektmätning",
      "Rengöring av värmeväxlare",
      "Rengörning av Switchade nätaggret",
      "Kontroll av nödstopp och interlock",
      "Upprättande av serviceprotokoll",
      "Serviceuppmärkning av utrustning",
      "Kontroll av säkerhetsrem",
      "Kontroll av possitionering av ledljus",
      "Kontroll av träffbildsmönster",
      "Kontroll av alla handneheters linser",
      "20 % på arbetstid för övriga reparationer",
      "20 % på resekostnader"
    ],
    additionalInfo: "Pris: 419 kr/månad"
  },
  "Splendor X": {
    title: "Standardservice och underhåll – Splendor X",
    details: [
      "Byte av avjoniserande DI-filter",
      "Byte av Smoke Evacuation-filter",
      "Rengöring av värmeväxlare i kylsystemet",
      "Rengöring av värmeväxlare i Splendor X",
      "Kontroll av optiska linser",
      "Påfyllning av destillerat avjoniserat kylvätska",
      "Spolning av pneumatisk krets",
      "Läckagekontroll",
      "Lasereffektmätning",
      "Rengörning av Switchade nätaggret",
      "Kontroll av nödstopp och interlock",
      "Upprättande av serviceprotokoll",
      "Serviceuppmärkning av utrustning",
      "Kontroll av säkerhetsrem",
      "Kontroll av träffbildsmönster",
      "Kontroll av alla handneheters linser",
      "20 % på arbetstid för övriga reparationer",
      "20 % på resekostnader"
    ],
    additionalInfo: "Pris: 709 kr/månad"
  },
  "Pento": {
    title: "Standardservice och underhåll – Pento",
    details: [
      "Byte av avjoniserande DI-filter",
      "Rengöring av värmeväxlare",
      "Kontroll av optiska linser",
      "Påfyllning av destillerat avjoniserat kylvätska",
      "Spolning av pneumatisk krets",
      "Läckagekontroll",
      "Lasereffektmätning",
      "Rengörning av Switchade nätaggret",
      "Kontroll av nödstopp och interlock",
      "Upprättande av serviceprotokoll",
      "Serviceuppmärkning av utrustning",
      "Kontroll av säkerhetsrem",
      "Kontroll av träffbildsmönster",
      "Kontroll av alla handneheters linser",
      "20 % på arbetstid för övriga reparationer",
      "20 % på resekostnader"
    ],
    additionalInfo: "Pris: 709 kr/månad"
  }
};